app/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

app/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordResetDoneView, PasswordResetCompleteView, PasswordChangeDoneView
from .views import HomeView, ProfileView, CustomSignupView, SignupSuccessView, CustomLoginView, CustomPasswordResetView, CustomPasswordResetConfirmView, CustomPasswordChangeView
from .forms import CustomLoginForm


app_name = 'users'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', CustomSignupView.as_view(), name='signup'),
    path('signup/success', SignupSuccessView.as_view(), name='signup_success'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('account/password-reset', CustomPasswordResetView.as_view(), name='password_reset'),
    path('account/password-reset/done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('account/password-reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('account/password-reset/complete', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('account/password-change', CustomPasswordChangeView.as_view(), name='password_change'),
    path('account/password-change/done', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
]

app/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator, MaxLengthValidator

# Create your models here.


class CustomUser(AbstractUser):
    username = models.CharField(max_length=120, unique=True, blank=False, null=False, validators=[
        MinLengthValidator(3),
        MaxLengthValidator(110)
    ])
    email = models.EmailField(unique=True, blank=False, null=False)

    def __str__(self):
        return self.username

app/users/forms.py
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordResetForm, PasswordChangeForm, SetPasswordForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

# Create your user forms here.


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Create account'))


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Login'))


class CustomPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Reset password'))


class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Set new password'))


class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Change password'))

app/users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from .forms import CustomUserCreationForm, CustomLoginForm, CustomPasswordChangeForm, CustomPasswordResetForm, CustomSetPasswordForm

# Create your views here.


class CustomLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'users/login.html'
    form_class = CustomLoginForm


class HomeView(TemplateView):
    template_name = 'users/home.html'


class ProfileView(TemplateView):
    template_name = 'users/profile.html'


class CustomSignupView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:signup_success')
    template_name = 'users/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('users:profile')
        return super().dispatch(request, *args, **kwargs)


class SignupSuccessView(TemplateView):
    template_name = 'users/signup_success.html'


class CustomPasswordResetView(PasswordResetView):
    form_class = CustomPasswordResetForm
    email_template_name = 'users/password_reset_email.html'
    template_name = 'users/password_reset.html'
    success_url = reverse_lazy('users:password_reset_done')


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = CustomSetPasswordForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class CustomPasswordChangeView(PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = 'users/password_change.html'
    success_url = reverse_lazy('users:password_change_done')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}{% endblock title %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% block styles %}{% endblock styles %}
</head>
<body>
    <header class="p-3 mb-3 border-bottom">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="{% url 'users:home' %}" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none px-2">
                    <i class="bi bi-mortarboard" style="font-size: 2rem; color: cornflowerblue;"></i>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'users:home' %}" class="nav-link px-2 link-secondary">Home</a></li>
                    <li><a href="#" class="nav-link px-2 link-body-emphasis">Empty link</a></li>
                    <li><a href="#" class="nav-link px-2 link-body-emphasis">Empty link</a></li>
                </ul>

                <div class="dropdown text-end">
                    {% if user.is_authenticated %}
                    <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://avatars.githubusercontent.com/u/50744737?v=4" alt="logo" width="32" height="32" class="rounded-circle">
                        <strong class="px-2">{{user.username}}</strong>
                    </a>
                    <ul class="dropdown-menu text-small">
                        <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:password_change' %}">Change password</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <form id="logout-form" method="post" action="{% url 'users:logout' %}" style="display:none;">
                            {% csrf_token %}
                        </form>
                        <li><a class="dropdown-item" href="/logout/" onclick="document.getElementById('logout-form').submit(); return false;">Log out</a></li>
                    </ul>
                    {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-outline-primary me-2" role="button">Login</a>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary" role="button">Sign-up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>

app/templates/users/home.html
{% extends "base.html" %}

{% block title %}home{% endblock title %}

{% block styles %}{% endblock styles %}

{% block content %}
<div class="container">
    <h1 class="display-6">Hello world</h1>
    {% if user.is_authenticated %}
        <p>hello, <a href="{% url 'users:profile' %}">{{ user.username }}</a></p>
        {% if user.is_superuser  %}
            <a href="{% url 'admin:index' %}">admin page</a>
        {% endif %}
        {% comment %} Now in django 5 i have to pass a logout form with csrf token {% endcomment %}
        <form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">logout</button>
        </form>
    {% else %}
        <a href="{% url 'users:login' %}">login</a> or <a href="{% url 'users:signup' %}">create new account</a>
        <p>if you forgot password -> <a href="{% url 'users:password_reset' %}">reset password</a></p>
    {% endif %}
</div>
{% endblock content %}

app/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}login{% endblock title %}

{% block styles %}{% endblock styles %}

{% block content %}
<div class="container">
    <h1 class="display-6">login page</h1>
    {% csrf_token %}
    {% crispy form %}
</div>
{% endblock content %}

app/templates/users/password_change.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}password change{% endblock title %}

{% block styles %}{% endblock styles %}

{% block content %}
<div class="container">
    <h1 class="display-6">Password change</h1>
    {% csrf_token %}
    {% crispy form %}
</div>
{% endblock content %}

app/templates/users/password_change_done.html
{% extends "base.html" %}

{% block title %}password change done{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="display-6">Password change done</h1>
    <p>Your password has been successfully changed!</p>
</div>
{% endblock content %}

app/templates/users/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}password reset{% endblock title %}

{% block styles %}{% endblock styles %}

{% block content %}
<div class="container">
    <h1 class="display-6">password reset</h1>
    {% csrf_token %}
    {% crispy form %}
</div>
{% endblock content %}

app/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block title %}password reset complete{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="display-6">Password reset complete</h1>
    <p>Your password has been successfully changed! You can <a href="{% url 'users:login' %}">login</a> now.</p>
</div>
{% endblock content %}

app/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}password reset confirm{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="display-6">Set new password</h1>
    {% crispy form %}
</div>
{% endblock content %}

app/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}password reset done{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="display-6">An email with password recovery instructions has been sent</h1>
    <p>We have sent you instructions for setting a new password to the specified email address (if there is such an address in our database). You should receive it soon.</p>
    <p>If you have not received the email, please make sure you have entered the email address you registered with and check your spam folder.</p>
</div>
{% endblock content %}

app/templates/users/password_reset_email.html
{% autoescape off %}You received this email because you requested a password reset for your account on {{ site_name }}.
Please go to the next page and create a new password:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Your username: {{ user.get_username }}
Thank you for using our website.
Site team {{ site_name }}
{% endautoescape %}

app/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}profile{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static "styles.css" %}">
{% endblock styles %}


{% block content %}
<div class="container">
    <h1 class="display-6">Profile page</h1>
    {% if user.is_authenticated %}
        <p>hi, {{ user.username }}!</p>
        <a href="{% url 'users:password_change' %}">change password</a>
    {% else %}
        <a href="{% url 'users:login' %}">login</a> or <a href="{% url 'users:signup' %}">create new account</a>
    {% endif %}
    <p class="main-text">static 'styles.css' text</p>
</div>
{% endblock content %}

app/templates/users/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}signup{% endblock title %}

{% block styles %}{% endblock styles %}

{% block content %}
<div class="container">
    <h1 class="display-6">signup page</h1>
    {% csrf_token %}
    {% crispy form %}
</div>
{% endblock content %}

app/templates/users/signup_success.html
{% extends "base.html" %}

{% block title %}signup success{% endblock title %}

{% block styles %}{% endblock styles %}

{% block content %}
<div class="container">
    <h1 class="display-6">signup success</h1>
    <p>Your account has been successfully created. You can <a href="{% url 'users:login' %}">login</a> now.</p>
</div>
{% endblock content %}